DROP TABLE IF EXISTS OrderItems;
DROP TABLE IF EXISTS Orders;
DROP TABLE IF EXISTS Products;
DROP TABLE IF EXISTS Customers;

CREATE TABLE Customers (
  CustomerID BIGSERIAL PRIMARY KEY,
  FirstName  TEXT NOT NULL,
  LastName   TEXT NOT NULL,
  Email      TEXT NOT NULL UNIQUE
);

CREATE TABLE Products (
  ProductID   BIGSERIAL PRIMARY KEY,
  ProductName TEXT NOT NULL UNIQUE,
  Price       NUMERIC(12,2) NOT NULL CHECK (Price >= 0)
);

CREATE TABLE Orders (
  OrderID     BIGSERIAL PRIMARY KEY,
  CustomerID  BIGINT NOT NULL REFERENCES Customers(CustomerID),
  OrderDate   TIMESTAMPTZ NOT NULL DEFAULT now(),
  TotalAmount NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK (TotalAmount >= 0)
);

CREATE TABLE OrderItems (
  OrderItemID BIGSERIAL PRIMARY KEY,
  OrderID     BIGINT NOT NULL REFERENCES Orders(OrderID) ON DELETE CASCADE,
  ProductID   BIGINT NOT NULL REFERENCES Products(ProductID),
  Quantity    INT NOT NULL CHECK (Quantity > 0),
  Subtotal    NUMERIC(12,2) NOT NULL CHECK (Subtotal >= 0)
);